export const initialOpportunities = [
  {
    id: 100,
    opportunity_name: "CISA Planning Programming Budgeting and Execution Support",
    agency_id: 1,
    primary_contact_id: 1,
    value: 6,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2022-04-01",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Business Line Priority",
    description: "OASIS TO: The Department of Homeland Security, Cybersecurity and Infrastructure Agency has a requirement for planning, programming, budgeting and execution support.  This will be issued via OASIS.",
    total_contract_value: 6,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2022-04-01",
    planned_rfp_release_date: "2021-03-01",
    planned_proposal_submission_date: "2022-03-11",
    contract_type: "TBD",
    solicitation_number: "F20210553648",
    acquisition_type: "TBD",
    duration: 51,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "541611 Admin. Management & General Management Consulting Services ($16.5M)",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/207325",
    govwin_id: "207325",
    notes: ""
  },
  {
    id: 101,
    opportunity_name: "USALearning? Education, Training Products, and Services",
    agency_id: 1,
    primary_contact_id: 1,
    value: 640000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2021-12-30",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Pre-Solicitation Notice Issued",
    priority: "Standard Priority",
    description: "OPM requires a contractor to provide integrated support of the Government's premier e-Learning provider and e-Training Program in the USALearning® program office. The contractor must be capable of providing various customized and configurable eLearning products and services to support multiple clients simultaneously. The provider must be agnostic to brand and specific systems and provide requirements-driven fully integrated learning ecosystem solutions to meet customer goals. These services shall include, but are not limited to the following:  Learning and Talent Management Systems (LMS) Learning Performance Systems Learner driven interfaces and portals support Learning development support for all types of learning environments, including structured (formal) or unstructured (informal) learning Learning Content Management Systems (LCMS) Course Development, Content Library provider, and SME curriculum development and delivery support Hosting Help Desk Services Online Forums (COPs, DM, KM, Social Media) Technical Support and Project Management Technical Training Assessments Organizational Needs Assessment Learning Records Data Warehouse",
    total_contract_value: 640000000,
    expected_revenue: 0,
    p_go: 25,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2022-04-01",
    planned_rfp_release_date: "2021-10-01",
    planned_proposal_submission_date: "",
    contract_type: "Firm Fixed Price (FFP)",
    solicitation_number: "",
    acquisition_type: "Small Business",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "541512 Computer Systems Design Services ($30M)",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/143625",
    govwin_id: "143625",
    notes: ""
  },
  {
    id: 102,
    opportunity_name: "USSPACECOM Additional Support for VTCs + Hours of Operations",
    agency_id: 1,
    primary_contact_id: 1,
    value: 153195,
    stage: "Closed Won",
    probability: 100,
    close_date: "2021-02-26",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "(Submitted) Best and Final Offer",
    priority: "Business Line Priority",
    description: "TO Scope true up",
    total_contract_value: 153195,
    expected_revenue: 153195,
    p_go: 75,
    forecast_category: "Closed",
    included_in_forecast: false,
    project_start_date: "2021-03-05",
    planned_rfp_release_date: "",
    planned_proposal_submission_date: "",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "TBD",
    duration: 3,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 103,
    opportunity_name: "NORAD and USNORTHCOM Enterprise Information Services (EIS) Operation and Maintenance (OM) (N2ITSM)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 90000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2022-12-01",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "IT Service Management - including the N-NC Service Catalog and those services that depend on these services for infrastructure, transport, and access. Data Centers, support for the NIPRNet and SIPRNet and CENTRIXS, and commercially provisioned unclassified networks, and Training",
    total_contract_value: 90000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-01-01",
    planned_rfp_release_date: "2022-11-01",
    planned_proposal_submission_date: "2022-11-30",
    contract_type: "Single Award IDIQ / SATOC",
    solicitation_number: "",
    acquisition_type: "Small Business",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "Other (please include in notes)",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/99764",
    govwin_id: "99764",
    notes: ""
  },
  {
    id: 104,
    opportunity_name: "FBI - DEVSECOPS - DigitalConsultants Team",
    agency_id: 1,
    primary_contact_id: 1,
    value: 10000000,
    stage: "Prospecting",
    probability: 0,
    close_date: "2022-08-01",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "Initial Capture Planning",
    priority: "Standard Priority",
    description: "DevSecOps support to FBI",
    total_contract_value: 10000000,
    expected_revenue: 0,
    p_go: 50,
    forecast_category: "Omitted",
    included_in_forecast: true,
    project_start_date: "2022-09-03",
    planned_rfp_release_date: "2022-05-27",
    planned_proposal_submission_date: "2022-06-30",
    contract_type: "TBD",
    solicitation_number: "LSU RFI 110620",
    acquisition_type: "Small Business",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 105,
    opportunity_name: "USAF - USAFA A&AS - CSSAR Extension",
    agency_id: 1,
    primary_contact_id: 1,
    value: 111765,
    stage: "Closed Won",
    probability: 100,
    close_date: "2020-12-18",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Active",
    priority: "Standard Priority",
    description: "",
    total_contract_value: 111765,
    expected_revenue: 111765,
    p_go: 50,
    forecast_category: "Closed",
    included_in_forecast: false,
    project_start_date: "2020-12-18",
    planned_rfp_release_date: "",
    planned_proposal_submission_date: "",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 12,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 106,
    opportunity_name: "USAF - USAFA A&AS - CyberWorx",
    agency_id: 1,
    primary_contact_id: 1,
    value: 694944,
    stage: "Closed Won",
    probability: 100,
    close_date: "2021-06-14",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "(Submitted) Best and Final Offer",
    priority: "Standard Priority",
    description: "",
    total_contract_value: 694944,
    expected_revenue: 694944,
    p_go: 50,
    forecast_category: "Closed",
    included_in_forecast: false,
    project_start_date: "2020-12-18",
    planned_rfp_release_date: "",
    planned_proposal_submission_date: "",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 12,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 107,
    opportunity_name: "USAF - USAFA A&AS - Aero Combined",
    agency_id: 1,
    primary_contact_id: 1,
    value: 528755,
    stage: "Closed Won",
    probability: 100,
    close_date: "2021-06-29",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Final RFP Issued",
    priority: "Standard Priority",
    description: "",
    total_contract_value: 528755,
    expected_revenue: 528755,
    p_go: 50,
    forecast_category: "Closed",
    included_in_forecast: false,
    project_start_date: "2020-12-18",
    planned_rfp_release_date: "",
    planned_proposal_submission_date: "",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 12,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 108,
    opportunity_name: "USCG Search And Rescue Optimal Planning System (SAROPS) Task Order",
    agency_id: 1,
    primary_contact_id: 1,
    value: 500000,
    stage: "Prospecting",
    probability: 0,
    close_date: "2021-12-09",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "",
    total_contract_value: 500000,
    expected_revenue: 0,
    p_go: 40,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2021-09-03",
    planned_rfp_release_date: "2020-10-02",
    planned_proposal_submission_date: "2022-05-02",
    contract_type: "Firm Fixed Price (FFP)",
    solicitation_number: "70Z04421R21000200",
    acquisition_type: "Unrestricted",
    duration: 12,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "541512 Computer Systems Design Services ($30M)",
    opportunity_link: "https://beta.sam.gov/opp/2a7108f4e85545dc84a937c71a550857/view",
    govwin_id: "137180",
    notes: ""
  },
  {
    id: 109,
    opportunity_name: "GMD Additional Staff Schriever AFB in Colorado Springs and/or Ft. Greely, AK",
    agency_id: 1,
    primary_contact_id: 1,
    value: 250000,
    stage: "Closed Lost",
    probability: 10,
    close_date: "2021-01-29",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Active",
    priority: "Business Line Priority",
    description: "GMD Additional Staff Schriever AFB in Colorado Springs and/or Ft. Greely, AK",
    total_contract_value: 250000,
    expected_revenue: 25000,
    p_go: 100,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2021-02-01",
    planned_rfp_release_date: "2020-11-20",
    planned_proposal_submission_date: "2020-12-10",
    contract_type: "Firm Fixed Price (FFP)",
    solicitation_number: "",
    acquisition_type: "Unrestricted",
    duration: 12,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 110,
    opportunity_name: "Chief Information Officer?Solutions and Partners 4 (CIO-SP4)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2022-11-03",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "Draft RFP Issued (or in full Capture)",
    priority: "Business Line Priority",
    description: "The Chief Information Officer?Solutions and Partners 4 (CIO-SP4) Government-Wide Acquisition Contract (GWAC) is a five-year Indefinite Delivery/Indefinite Quantity (IDIQ) contract with a five-year optional period; with a fifteen-year period of performance. Task Orders awarded on the last day of the GWAC ordering period in the five-year option can perform for up to five years. Therefore, the period of performance for the GWAC is 15 years. This contract is intended to provide Information Technology (IT) solutions and services as defined in FAR 2.101(b) and further clarified in the Clinger-Cohen Act of 1996. These IT solutions and services include, but are not limited to, health and  biomedical-related IT services to meet scientific, health, administrative,  operational, managerial and information management requirements. The contract also contains general IT services partly because medical systems are increasingly integrated within a broader IT architecture, requiring a systems approach to their implementation and a sound infrastructure for their operation.",
    total_contract_value: 1,
    expected_revenue: 0,
    p_go: 70,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2022-12-01",
    planned_rfp_release_date: "2021-04-29",
    planned_proposal_submission_date: "2022-02-11",
    contract_type: "Hybrid",
    solicitation_number: "75N98120R00002",
    acquisition_type: "8(a)",
    duration: 120,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "541990 All Other Professional, Scientific& Technical Services ($16.5M)",
    opportunity_link: "",
    govwin_id: "177161",
    notes: ""
  },
  {
    id: 111,
    opportunity_name: "ITES-4 (Services)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-06-03",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "ITES-4 Information Technology Enterprise Support",
    total_contract_value: 1,
    expected_revenue: 0,
    p_go: 5,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-07-31",
    planned_rfp_release_date: "2022-12-01",
    planned_proposal_submission_date: "2022-12-30",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "Unrestricted",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/64990",
    govwin_id: "",
    notes: ""
  },
  {
    id: 112,
    opportunity_name: "Responsive Strategic Sourcing for Services (RS4)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2025-03-31",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "Responsive Strategic Sourcing for Services",
    total_contract_value: 1,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-12-29",
    planned_rfp_release_date: "2023-03-01",
    planned_proposal_submission_date: "2023-03-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 113,
    opportunity_name: "Polaris Small Business GWAC",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2022-08-03",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Draft RFP Issued (or in full Capture)",
    priority: "Standard Priority",
    description: "Polaris is a family of Multiple Award, IDIQ contracts to provide customized IT services and IT service-based solutions and IT services-based solutions. The principal nature of any resulting task order procurement must be for IT services; however, ancillary support may be included when it is integral to and necessary for the IT services-based effort.",
    total_contract_value: 1,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2022-11-01",
    planned_rfp_release_date: "2022-03-25",
    planned_proposal_submission_date: "2022-05-13",
    contract_type: "TBD",
    solicitation_number: "47QTCB22R0001",
    acquisition_type: "Small Business",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "541512 Computer Systems Design Services ($30M)",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/214987",
    govwin_id: "214987",
    notes: ""
  },
  {
    id: 114,
    opportunity_name: "SPACEFORCE > GPS Interference Detection",
    agency_id: 1,
    primary_contact_id: 1,
    value: 15000,
    stage: "Closed Won",
    probability: 100,
    close_date: "2021-01-22",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "Proposal Submitted",
    priority: "Standard Priority",
    description: "Provide engineering options regarding interference effecting the operations of the GPS antenna in Building 400 on Schriever AFB, CO. The ultimate goal is to identify possible sources causing the interference and provide recommendation, as applicable, for remediation of the cause.",
    total_contract_value: 15000,
    expected_revenue: 15000,
    p_go: 80,
    forecast_category: "Closed",
    included_in_forecast: false,
    project_start_date: "2021-03-31",
    planned_rfp_release_date: "2020-12-31",
    planned_proposal_submission_date: "2021-01-07",
    contract_type: "Firm Fixed Price (FFP)",
    solicitation_number: "",
    acquisition_type: "Unrestricted",
    duration: 4,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 115,
    opportunity_name: "Perimeter Acquisition Radar Attack Characterizations System (PARCS)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 52000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-01-01",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Initial Capture Planning",
    priority: "Standard Priority",
    description: "The Perimeter Acquisition Radar Attack Characterization System (PARCS) is a single-faced, multi-function, UHF-Band, phased-array radar located at Cavalier Air Force Station, N.D.   The primary mission of PARCS is to keep watch for sea-launched and intercontinental ballistic missiles launched toward North America, and to collect Launch and Predicted Impact (L&PI) data, generally defined as missile warning (MW) data. The secondary mission of PARCS is to provide data concerning space launches and orbiting objects as a collateral sensor for the Space Surveillance Network (SSN).",
    total_contract_value: 52000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-02-02",
    planned_rfp_release_date: "2022-01-07",
    planned_proposal_submission_date: "2022-02-28",
    contract_type: "TBD",
    solicitation_number: "FA2517PARCS2023",
    acquisition_type: "Unrestricted",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/172534?sm=OTk1OWEzMWMtMzIxYi00ZWNhLTgwMTUtNjRiM2QwODI1OTk3",
    govwin_id: "172534",
    notes: ""
  },
  {
    id: 116,
    opportunity_name: "A2/6 Consolidated Cyber Advisory and Assistance Services (A&AS)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 13000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-06-01",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "(Submitted) Market Research/Sources Sought",
    priority: "Standard Priority",
    description: "OASIS TO: A&AS for Intelligence, Surveillance, and Reconnaissance (ISR) Chief Information Officer (CIO) Support Services. Support with AF A2/6 MAJCOM/A2s and subordinate units for ongoing and emerging core components of the information architecture capability system that exits today in support of the warfighter needs in the AOR for timely fused intelligence information. Provides multi-layer analysis to address rapid tactical missions.",
    total_contract_value: 13000000,
    expected_revenue: 0,
    p_go: 20,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-06-01",
    planned_rfp_release_date: "2022-11-01",
    planned_proposal_submission_date: "2022-11-28",
    contract_type: "Hybrid",
    solicitation_number: "",
    acquisition_type: "Unrestricted",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "205085",
    notes: ""
  },
  {
    id: 117,
    opportunity_name: "24: SIPRNet and Global Command and Control System Administration (GCCS) support services",
    agency_id: 1,
    primary_contact_id: 1,
    value: 23000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2024-11-01",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "Provide technical solutions and cost estimate for the installation of SIPRNET projects; expansion of existing VoSIP network infrastructure (Call Manager) and secure room requirements for classified network equipment. Provide SIPRNET systems support relating to the day-to-day operations of fiberbased and copper-based infrastructure. Support analysis of network performance (i.e. traffic load, connect time, transmission speeds, packet sizes, and throughput. Support site surveys, development of network designs, support troubleshooting, configuration control, and testing. Train military counterparts in both network management and configuration management. Support preparation and maintenance of local accreditation packages for SIPRNET and VoSIP architecture.",
    total_contract_value: 23000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2025-11-01",
    planned_rfp_release_date: "2024-05-01",
    planned_proposal_submission_date: "2024-05-28",
    contract_type: "Hybrid",
    solicitation_number: "FA521520R7004",
    acquisition_type: "Small Business",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/186038",
    govwin_id: "186038",
    notes: ""
  },
  {
    id: 118,
    opportunity_name: "USAFA Creative Services",
    agency_id: 1,
    primary_contact_id: 1,
    value: 5000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-03-31",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "The Department of the Air Force, U.S. Air Force Academy, Communications and Outreach Directorate, Public Affairs Office may have a continuing requirement for videography, photography, and graphic design services.",
    total_contract_value: 5000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-03-31",
    planned_rfp_release_date: "2023-02-01",
    planned_proposal_submission_date: "2023-03-01",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "Small Business",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/192124",
    govwin_id: "192124",
    notes: ""
  },
  {
    id: 119,
    opportunity_name: "Space Operations System Engineering Technical Assistance",
    agency_id: 1,
    primary_contact_id: 1,
    value: 11000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-01-01",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "OASIS: The Department of the Air Force, Office of the Chief of Staff of the Air Force (CSAF), Space Operations Directorate's (HAF/A11) may have a continuing requirement for System Engineering Technical Assistance support.  TO OASIS SB, only one offer submitted, follow-on will be procured in the same manner.",
    total_contract_value: 11000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-01-01",
    planned_rfp_release_date: "2022-11-01",
    planned_proposal_submission_date: "2022-11-30",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "Small Business",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/192045",
    govwin_id: "192045",
    notes: ""
  },
  {
    id: 120,
    opportunity_name: "Consolidated Air Force Satellite Control Network (AFSCN) Modifications, Maintenance & Ops (CAMMO) (STORMS)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 100000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-10-01",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "The Department of the Air Force, Air Force Space Command, Space and Missiles Systems Center, Range and Network Systems Division may have a continuing requirement for a Consolidated Air Force Satellite Control Network (AFSCN) Modifications, Maintenance & Operations (CAMMO) contract.",
    total_contract_value: 100000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-11-01",
    planned_rfp_release_date: "2023-05-01",
    planned_proposal_submission_date: "2023-05-30",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "Unrestricted",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/178448",
    govwin_id: "178448",
    notes: ""
  },
  {
    id: 121,
    opportunity_name: "National Air and Space Intelligence Center (NASIC) Advisory and Assistance Services III (A&ASIII) GS Task Order 1",
    agency_id: 1,
    primary_contact_id: 1,
    value: 80000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-10-02",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "BPA: The Department of the Air Force, National Air and Space Intelligence Center (NASIC), Geospatial and Signatures Intelligence Group (GS) has a follow-on requirement for Measurement and Signature Intelligence Geospatial and Intelligence advisory and assistance services.",
    total_contract_value: 80000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-11-02",
    planned_rfp_release_date: "2023-03-01",
    planned_proposal_submission_date: "2023-03-30",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "Small Business",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/199077",
    govwin_id: "199077",
    notes: ""
  },
  {
    id: 122,
    opportunity_name: "Encore IV",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-01-01",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "Follow on Encore contract with DISA",
    total_contract_value: 1,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-01-01",
    planned_rfp_release_date: "2023-01-01",
    planned_proposal_submission_date: "2023-11-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 123,
    opportunity_name: "DISA  Systems Engineering, Technology, and Innovation (SETI)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2024-03-03",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "SETI is a new multiple-award task order contract (MATOC) vehicle for the Department of Defense. It is based on innovation as a priority to solve the complex IT engineering and developmental requirements for DISA and its mission partners. SETI will consolidate and streamline critical engineering expertise to research, design, develop, implement, integrate, and optimize DOD IT capabilities, systems, and solutions.",
    total_contract_value: 1,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2025-01-01",
    planned_rfp_release_date: "2024-01-01",
    planned_proposal_submission_date: "2024-02-01",
    contract_type: "Multi Award IDIQ / MATOC",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 124,
    opportunity_name: "AS: DoS Support Services Acquisition Center",
    agency_id: 1,
    primary_contact_id: 1,
    value: 10000000,
    stage: "Prospecting",
    probability: 0,
    close_date: "2023-02-01",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "Initial Capture Planning",
    priority: "Standard Priority",
    description: "Team with Metrostar for DoS Acquisition Center software development opportunity (60 People)",
    total_contract_value: 10000000,
    expected_revenue: 0,
    p_go: 20,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-03-01",
    planned_rfp_release_date: "2023-01-01",
    planned_proposal_submission_date: "2023-01-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "TBD",
    duration: 48,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 125,
    opportunity_name: "24: Federal Protective Services Training Support",
    agency_id: 1,
    primary_contact_id: 1,
    value: 3000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2024-04-01",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Initial Capture Planning",
    priority: "Standard Priority",
    description: "The Department of Homeland Security (DHS), Federal Protective Services (FPS) may have a continuing requirement for instructors to support the current full-time employee instructor staff in the Training and Professional Development division at the Federal Law Enforcement Training Centers in Glynco, GA.",
    total_contract_value: 3000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2024-01-29",
    planned_rfp_release_date: "2024-01-01",
    planned_proposal_submission_date: "2024-01-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "Small Business",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/187945",
    govwin_id: "187945",
    notes: ""
  },
  {
    id: 126,
    opportunity_name: "24: Air Advisor Support",
    agency_id: 1,
    primary_contact_id: 1,
    value: 12000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2024-04-01",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "OASIS: Air Force, Office of the Chief of Staff of the Air Force, Directorate of Training and Readiness - Mobility A3TM may have a continuing requirement for Air Advisor support services.",
    total_contract_value: 12000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2024-01-01",
    planned_rfp_release_date: "2024-03-01",
    planned_proposal_submission_date: "2024-03-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/199626?sm=MTY3YWY4YWQtN2YwNi00ZDkzLWI0NjEtZWI1NDY2YmIxMzAx",
    govwin_id: "199626",
    notes: ""
  },
  {
    id: 127,
    opportunity_name: "23: Polar Security Cutter System Engineering Technical Assistance Support for the  Asset Project Office (SETA APO)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-05-01",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "OASIS: DHS, U.S. Coast Guard, Asset Project Office (APO) ongoing requirement for Integrated Logistics System Engineering Technical Assistance and Project Management for the Heavy Polar Icebreaker (HPIB) Program.",
    total_contract_value: 1000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-01-01",
    planned_rfp_release_date: "2023-02-01",
    planned_proposal_submission_date: "2023-02-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "Unrestricted",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/196295",
    govwin_id: "196295",
    notes: ""
  },
  {
    id: 128,
    opportunity_name: "23: MODELING AND SIMULATION SOFTWARE DEVELOPMENT OPERATION AND SUSTAINMENT (M&S)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 24000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-08-01",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "OASIS: The Department of the Air Force, Air Force Materiel Command, Air Force Nuclear Weapons Center has a requirement for Modeling & Simulation Software Development, Operation and Sustainment.",
    total_contract_value: 24000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2024-01-01",
    planned_rfp_release_date: "2023-02-01",
    planned_proposal_submission_date: "2023-02-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 48,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/188930",
    govwin_id: "188930",
    notes: ""
  },
  {
    id: 129,
    opportunity_name: "24: Accounting and Administrative Support Services at the Aviation Logistics Center",
    agency_id: 1,
    primary_contact_id: 1,
    value: 4000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2024-04-01",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "OASIS SB: The Department of Homeland Security (DHS), US Coast Guard's, (USCG) may have a continuing requirement for accounting and administrative support services for the Aviation Logistics Center, in Elizabeth City, NC.",
    total_contract_value: 4000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2025-01-01",
    planned_rfp_release_date: "2024-02-01",
    planned_proposal_submission_date: "2024-02-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/197090",
    govwin_id: "197090",
    notes: ""
  },
  {
    id: 130,
    opportunity_name: "23: Operations and Maintenance of Configuration and Maintenance Management System - Asset Computerized Maintenance Syste",
    agency_id: 1,
    primary_contact_id: 1,
    value: 15000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-09-01",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "The Department of Homeland Security, United States Coast Guard, Coast Guard Engineering and Industrial Support Division may have an ongoing requirement for the operation and maintenance of its Configuration and Maintenance Management (CMM) system currently referred to as Asset Computerized Maintenance System (ACMS).",
    total_contract_value: 15000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2024-01-01",
    planned_rfp_release_date: "2023-03-01",
    planned_proposal_submission_date: "2023-03-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/185911",
    govwin_id: "185911",
    notes: ""
  },
  {
    id: 131,
    opportunity_name: "HQ AF Space Command Product Development Support for the Ready Spacecrew Program and Space Mission Force (RSP)(SMF)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 12000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2024-01-01",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "OASIS SB: The Department of the Air Force, Air Force Space Command (AFSPC), HQ AFSPC Integrated Air, Space, Cyberspace and ISR Operations Directorate may have a continuing requirement for training product development support.",
    total_contract_value: 12000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2024-02-01",
    planned_rfp_release_date: "2023-10-01",
    planned_proposal_submission_date: "2023-10-30",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "Small Business",
    duration: 48,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/185478?sm=MjlmOWI1Y2UtNDIwNy00ZGE5LWIxYTEtYjJkZjQzOTk4MDk4",
    govwin_id: "185478",
    notes: ""
  },
  {
    id: 132,
    opportunity_name: "CIO ISR ADVISORY AND ASSISTANCE SERVICES",
    agency_id: 1,
    primary_contact_id: 1,
    value: 3000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-06-01",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "The Department of the Air Force, Office of the Chief of Staff, ISR and Cyber Effects Operations (A2/A6) may have a continuing requirement for A&AS support.",
    total_contract_value: 3000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-01-01",
    planned_rfp_release_date: "2022-11-01",
    planned_proposal_submission_date: "2022-11-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 48,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/205085",
    govwin_id: "205085",
    notes: ""
  },
  {
    id: 133,
    opportunity_name: "National Continuity Program Communications Division Engineering and Technical Support",
    agency_id: 1,
    primary_contact_id: 1,
    value: 2000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-07-03",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "OASIS: The Department of Homeland Security, Federal Emergency Management Agency (FEMA) may have a continuing requirement for National Continuity Programs (NCP), Continuity Communications Division (CCD), Engineering and Technical Support Services.",
    total_contract_value: 2000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-01-01",
    planned_rfp_release_date: "2023-04-01",
    planned_proposal_submission_date: "2023-04-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 48,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/193869",
    govwin_id: "193869",
    notes: ""
  },
  {
    id: 134,
    opportunity_name: "23: 18th Air Force Program Management Support",
    agency_id: 1,
    primary_contact_id: 1,
    value: 4000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-09-01",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "OASIS SB Pool: The Department of the Air Force, Air Mobility Command, 18th Air Force, 375th Air Mobility Wing may have a continuing requirement for program management support.",
    total_contract_value: 4000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-01-01",
    planned_rfp_release_date: "2023-06-01",
    planned_proposal_submission_date: "2023-08-01",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 48,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/189303",
    govwin_id: "189303",
    notes: ""
  },
  {
    id: 135,
    opportunity_name: "HR Contact Center Modernization",
    agency_id: 1,
    primary_contact_id: 1,
    value: 500000,
    stage: "Prospecting",
    probability: 0,
    close_date: "2022-10-02",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "There is an ongoing effort to modernize their HR shared service center.",
    total_contract_value: 500000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2021-11-01",
    planned_rfp_release_date: "2022-09-01",
    planned_proposal_submission_date: "2022-09-30",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 136,
    opportunity_name: "Enterprise Cyber Capabilities (EC2)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-01-01",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "Final RFP Issued",
    priority: "Standard Priority",
    description: "New requirement for The scope of this effort includes supporting and enabling activities such as cyber operations, command and control, cyber planning, cyber security, cyber analysis, full spectrum testing, TTP development, modeling and simulation, cyber mission essential support, threat assessment support, targeting and analysis support, real time operation and integration activities, software and tool development, vulnerability research, intrusion detection and prevention support, cyber qualification training, and strategic management support which enable fulfillment of the Air Force cyber mission.",
    total_contract_value: 1,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-02-01",
    planned_rfp_release_date: "2022-09-23",
    planned_proposal_submission_date: "2022-12-02",
    contract_type: "TBD",
    solicitation_number: "FA877322R0005",
    acquisition_type: "Small Business",
    duration: 120,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "541330 Engineering Services ($16.5M)",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/184301",
    govwin_id: "184301",
    notes: ""
  },
  {
    id: 137,
    opportunity_name: "USDA FPAC - Farmers.Gov O&M Support - Base",
    agency_id: 1,
    primary_contact_id: 1,
    value: 2349465,
    stage: "Closed Won",
    probability: 100,
    close_date: "2022-06-27",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Active",
    priority: "Business Line Priority",
    description: "3 Year Contract - Base + 2 - The USDA's Farm Production and Conservation (FPAC) mission area offers production and conservation tools, financial assistance, and technical advice along with commodity, lending, and disaster programs for America?s farmers, ranchers, and private forest landowners. With offices that serve customers in every state and county, FPAC agency employees deliver personalized customer service locally to producers, a service valued by producers and partners alike. Farmers.gov was developed in 2018 as an online platform to improve customer experience and access to FPAC programs. It enables customers to conduct business with the Department and learn about programs and services offered through a website that is user-focused and customer service driven.",
    total_contract_value: 2349465,
    expected_revenue: 2349465,
    p_go: 100,
    forecast_category: "Closed",
    included_in_forecast: true,
    project_start_date: "2022-06-30",
    planned_rfp_release_date: "2022-05-17",
    planned_proposal_submission_date: "2022-06-09",
    contract_type: "Firm Fixed Price (FFP)",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 12,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 138,
    opportunity_name: "Technical Services Support (TSS) 2 Contract for  MyNavyHR Enterprise",
    agency_id: 1,
    primary_contact_id: 1,
    value: 20000000,
    stage: "Closed Lost",
    probability: 75,
    close_date: "2022-11-01",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "Draft RFP Issued (or in full Capture)",
    priority: "Standard Priority",
    description: "N1 requires technical support services for N16 CIO statutory oversight responsibilities, which includes IT Enterprise Architecture (EA), Portfolio Management (PfM), Governance Operations, and IM/IT Requirements Management.   \t The effort will encompass all aspects of N16 CIO and IM/IT Requirements at the Echelon I level, as well as at the Echelon II/III level at BUPERS/NPC, CNRC, and NETC. The support will require direct interaction with action officers and program managers across the MyNavyHR enterprise as well as all other Navy Enterprises and Enablers to support N1 IM/IT responsibilities.  In addition, support will require the analysis and refinement of legacy IS sustainment and the sustainment of the optimized IS construct.  Finally, the contractors will provide a continuum of on-site and off-site support to N1?s action officers, program managers and analysts at all echelon levels, for multiple commands, and at multiple geographic locations.",
    total_contract_value: 20000000,
    expected_revenue: 15000000,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2022-12-01",
    planned_rfp_release_date: "2022-06-01",
    planned_proposal_submission_date: "2022-06-11",
    contract_type: "TBD",
    solicitation_number: "N0018921RZ032",
    acquisition_type: "Unrestricted",
    duration: 48,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "541512 Computer Systems Design Services ($30M)",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 139,
    opportunity_name: "Consolidated Operations, Management, Engineering, and Test (COMET)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 5000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-11-03",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Proposal Submitted",
    priority: "Standard Priority",
    description: "Manage and perform activities to accomplish ground processing for launch vehicles, spacecraft and payloads in support of the ISS, GSDO, SLS and MPCV Programs and LSP spacecraft customers. The contractor shall manage and perform Spaceport Services for existing and emerging programs, commercial entities and other government agencies as designated by the Government.",
    total_contract_value: 5000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-12-03",
    planned_rfp_release_date: "2022-02-16",
    planned_proposal_submission_date: "2022-04-25",
    contract_type: "TBD",
    solicitation_number: "80KSC022R0004",
    acquisition_type: "Unrestricted",
    duration: 48,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "Other (please include in notes)",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/165798",
    govwin_id: "165798",
    notes: ""
  },
  {
    id: 140,
    opportunity_name: "Mission Partner Environment Consolidation (MPC2 &I2S)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1000000,
    stage: "Prospecting",
    probability: 0,
    close_date: "2024-07-22",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "Pre-Solicitation Notice Issued",
    priority: "Standard Priority",
    description: "Team to support CACI",
    total_contract_value: 1000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2024-08-01",
    planned_rfp_release_date: "2024-06-06",
    planned_proposal_submission_date: "2024-06-28",
    contract_type: "TBD",
    solicitation_number: "CDM-2020-1",
    acquisition_type: "Unrestricted",
    duration: 48,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "541512 Computer Systems Design Services ($30M)",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/188804",
    govwin_id: "188804",
    notes: ""
  },
  {
    id: 141,
    opportunity_name: "Information Technology (IT) Support Service (ITSS) for the Office of Naval Research",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2026-12-01",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "(Submitted) Market Research/Sources Sought",
    priority: "Standard Priority",
    description: "FedConnect: Request for Information for Information Technology (IT) Support Service for the Office of Naval Research",
    total_contract_value: 1,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2026-12-01",
    planned_rfp_release_date: "2026-12-01",
    planned_proposal_submission_date: "2026-12-01",
    contract_type: "TBD",
    solicitation_number: "N00014-21-R-0008",
    acquisition_type: "8(a)",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 142,
    opportunity_name: "USAF NSSI - Sigmatech - BASE",
    agency_id: 1,
    primary_contact_id: 1,
    value: 171635,
    stage: "Closed Won",
    probability: 100,
    close_date: "2021-05-01",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "(Submitted) Best and Final Offer",
    priority: "Business Line Priority",
    description: "Recompete of existing work as a sub",
    total_contract_value: 171635,
    expected_revenue: 171635,
    p_go: 100,
    forecast_category: "Closed",
    included_in_forecast: true,
    project_start_date: "2021-05-01",
    planned_rfp_release_date: "",
    planned_proposal_submission_date: "",
    contract_type: "Time & Material (T&M)",
    solicitation_number: "",
    acquisition_type: "Unrestricted",
    duration: 12,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 143,
    opportunity_name: "Air Force DCGS Requirements Support Services (ADReSS)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 10000000,
    stage: "Prospecting",
    probability: 0,
    close_date: "2024-11-01",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Initial Capture Planning",
    priority: "Standard Priority",
    description: "This Sources Sought Synopsis (SSS) is being conducted to identify potential sources that may possess the expertise, capabilities, and experience to meet the requirements to fulfill the capabilities and services identified below in support of the missions and operations carried out by Air Force Distributed Common Ground Systems (AF DCGS)",
    total_contract_value: 10000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: true,
    project_start_date: "2024-12-01",
    planned_rfp_release_date: "2024-10-01",
    planned_proposal_submission_date: "2024-10-28",
    contract_type: "TBD",
    solicitation_number: "FA8527-21-R-0013",
    acquisition_type: "TBD",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/202632",
    govwin_id: "202632",
    notes: ""
  },
  {
    id: 144,
    opportunity_name: "GSA Federal Acquisition Service?s (FAS) Best-in-Class Multiple Agency Contract (BIC MAC) Services IDIQ",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1,
    stage: "Prospecting",
    probability: 0,
    close_date: "2023-03-23",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "(Submitted) Market Research/Sources Sought",
    priority: "Standard Priority",
    description: "The U.S. General Services Administration (GSA) is developing a new indefinite-delivery indefinite-quantity (IDIQ) best-in-class (BIC) multi-agency contract (MAC) contract program to support federal agencies? procurement requirements for services. GSA?s goal is to establish a BIC MAC that is flexible, can evolve and expand over time, and supports a broad range of mission and service needs through a highly qualified industrial base. Led by the Federal Acquisition Service?s (FAS) Office of Professional Services and Human Capital Categories (PSHC) the contract program will be developed with collaborative engagement from federal ordering agencies, industry partners, multiple FAS programs and offices, the Small Business Administration, and other key stakeholders.",
    total_contract_value: 1,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-04-01",
    planned_rfp_release_date: "2023-01-23",
    planned_proposal_submission_date: "2023-02-23",
    contract_type: "Multi Award IDIQ / MATOC",
    solicitation_number: "47QRCA21N0001",
    acquisition_type: "8(a)",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/201043",
    govwin_id: "201043",
    notes: ""
  },
  {
    id: 145,
    opportunity_name: "DIA Jupiter Station Rapid Prototyping Project and Mission Support",
    agency_id: 1,
    primary_contact_id: 1,
    value: 3000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-03-17",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Initial Capture Planning",
    priority: "Standard Priority",
    description: "eBuy OASIS Pool 3 8(a):To provide necessary contractor support required to advance the rapid prototyping mission of the Defense Intelligence Agency (DIA), Directorate for Science and Technology (ST), Office of Advanced Technologies Intelligence (ATI), Quick Reaction Development Division (ATI7) referred to as ?Jupiter Station? (JS).  The intent of this acquisition is to provide the necessary labor, purchasing abilities, and access to ancillary services so that ATI7 can meet the rapid research and development timelines levied upon them to meet real world mission and operational requirements.",
    total_contract_value: 3000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2022-04-30",
    planned_rfp_release_date: "2022-10-01",
    planned_proposal_submission_date: "2022-10-30",
    contract_type: "TBD",
    solicitation_number: "RFQ1481122",
    acquisition_type: "8(a)",
    duration: 36,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "",
    notes: ""
  },
  {
    id: 146,
    opportunity_name: "One Acquisition Solution for Integrated Services (OASIS+) 8(a)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1,
    stage: "Prospecting",
    probability: 90,
    close_date: "2025-11-03",
    entityId: 1,
    forecastGroupId: 3,
    capabilities: [],
    opportunity_status: "Final RFP Issued",
    priority: "Aleut Federal Priority",
    description: "OASIS Recompete and updated vehicle. This contract is planned to replace the One Acquisition Solution for Integrated Services (OASIS) acquisition vehicle and it will include functional areas from other GSA contracts such as BMO (Building Maintenance and Operation) and HCaTS (Human Capital Training Solution).",
    total_contract_value: 1,
    expected_revenue: 1,
    p_go: 20,
    forecast_category: "Forecast",
    included_in_forecast: false,
    project_start_date: "2025-11-03",
    planned_rfp_release_date: "2023-07-01",
    planned_proposal_submission_date: "2023-09-21",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/201043",
    govwin_id: "201043",
    notes: ""
  },
  {
    id: 147,
    opportunity_name: "Small Business Enterprise Applications Solutions IDIQ (SBEAS)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 1,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-06-01",
    entityId: 1,
    forecastGroupId: 4,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "The purpose of this Indefinite Delivery/Indefinite Quantity (IDIQ) Contract is to provide a vehicle for customers to access a wide range of Information Technology (IT) Network Centric services and solutions that support the IT lifecycle. While the SBEAS contract is mandatory use for the Air Force, this contract vehicle may be used by all other agencies that support an Air Force requirement.The purpose of this Indefinite Delivery/Indefinite Quantity (IDIQ) Contract is to provide a vehicle for customers to access a wide range of Information Technology (IT) Network Centric services and solutions that support the IT lifecycle. While the SBEAS contract is mandatory use for the Air Force, this contract vehicle may be used by all other agencies that support an Air Force requirement.",
    total_contract_value: 1,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-07-01",
    planned_rfp_release_date: "2023-04-01",
    planned_proposal_submission_date: "2023-04-28",
    contract_type: "TBD",
    solicitation_number: "",
    acquisition_type: "8(a)",
    duration: 48,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "",
    govwin_id: "146278",
    notes: ""
  },
  {
    id: 148,
    opportunity_name: "Implementation Services for the National Correspondence Management System (NCMS)",
    agency_id: 1,
    primary_contact_id: 1,
    value: 25000000,
    stage: "Closed Lost",
    probability: 0,
    close_date: "2023-01-22",
    entityId: 1,
    forecastGroupId: 1,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "The U.S. Department of Agriculture, Forest Service has a requirement for personnel, equipment, tools, materials, supervision, and other items and non-personal services necessary to perform National Correspondence Management System (NCMS) Implementation Service.",
    total_contract_value: 25000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2023-02-01",
    planned_rfp_release_date: "2022-09-01",
    planned_proposal_submission_date: "2022-09-30",
    contract_type: "TBD",
    solicitation_number: "12760420Q0185_1",
    acquisition_type: "8(a)",
    duration: 60,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "Other (please include in notes)",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/198098",
    govwin_id: "198098",
    notes: ""
  },
  {
    id: 149,
    opportunity_name: "OneRD Guaranteed Loan Program",
    agency_id: 1,
    primary_contact_id: 1,
    value: 2000000,
    stage: "Prospecting",
    probability: 0,
    close_date: "2022-10-03",
    entityId: 1,
    forecastGroupId: 2,
    capabilities: [],
    opportunity_status: "Initial Prospect/Forecast",
    priority: "Standard Priority",
    description: "The U.S. Department of Agriculture, Rural Development (USDA RD) has a requirement to develop an automated system to support application intake, review, processing, and loan guarantee issuing and servicing under the OneRD Guaranteed Loan Program Regulation. This regulation combines regulations previously governing four existing commercial loan guarantee programs.",
    total_contract_value: 2000000,
    expected_revenue: 0,
    p_go: 10,
    forecast_category: "Omitted",
    included_in_forecast: false,
    project_start_date: "2022-11-01",
    planned_rfp_release_date: "2022-09-03",
    planned_proposal_submission_date: "2022-09-30",
    contract_type: "TBD",
    solicitation_number: "USDARD070820",
    acquisition_type: "8(a)",
    duration: 48,
    budget_confirmed: false,
    discovery_completed: false,
    roi_analysis_completed: false,
    primary_business_line: "Technology Services",
    primary_naics_code: "TBD",
    opportunity_link: "https://iq.govwin.com/neo/opportunity/view/194874",
    govwin_id: "194874",
    notes: ""
  }
];
